name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 128.199.36.43
        username: root
        password: 983F07553f
        port: 22
        script: |
          cd /root/gestus/backend
          git stash
          git stash drop
          git pull -v origin master

