name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 68.183.113.95
        username: root
        password: 983F07553f
        port: 22
        script: |
          cd /root/edificios/backend
          git pull origin master
          docker-compose build backend
          docker-compose up -d backend
