name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 68.183.113.95
        username: root
        password: 983F07553f
        port: 22
    - name: remote push
      run: |
          cd ~/edificios/backend
          git pull origin master
        
    - name: build docker-compose 
      run: |
            cd ~/edificios
            docker-compose build backend
    - name: restart docker-compose
      run: |
            cd /root/edificios
            docker-compose up -d backend
