name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_URL }}
        username: root
        password: ${{ secrets.ROOT_PASSWORD }}
        port: 22
    - name: remote push
      run: |
          cd /root/edificios/backend
          git pull remote origin master
        
    - name: build docker-compose 
      run: |
            cd /root/edificios
            docker-compose build backend
    - name: restart docker-compose
      run: |
            cd /root/edificios
            docker-compose up -d backend
